优化消息吞空白字符问题
Icalingua/Icalingua pull request #118
Opened 2021-08-07 04:51 UTC by ForkKILLET

将文本消息用 pre 标签包裹

2021-08-07 05:48 UTC, Clansty commented
显示消息内容的位置不止这里，还需要解决换行问题（可以通过 CSS）

另外请将 PR 发送至 dev 分支

2021-08-07 05:49 UTC, Clansty requested changes
需要修改其它显示消息的位置

2021-08-07 08:51 UTC, CoelacanthusHex commented
目前似乎是会把换行符统统转成空格（没错这东西搞炸了窝的PGP消息格式

2021-08-07 08:52 UTC, Clansty commented
@CoelacanthusHex 没有吧，换行符正常换行的啊

2021-08-08 02:44 UTC, ForkKILLET commented
> 需要修改其它显示消息的位置

我刚学 vue，昨天看完了教程，所以没能及时修改  

我找到可能需要修改的有 `FormatMessage.vue` 中 `{{ message.value }}` 还有 `{{ formattedContent }}` 和 `RoomEntry.vue` 中 `{{ desc }}`，不知道全不全

2021-08-08 05:58 UTC, ForkKILLET commented
`{{ desc }}` 似乎不需要改

2021-08-08 06:40 UTC, ForkKILLET commented
请问 `yarn dev` 第一次能运行，卡死后第二次报错并白屏：

```
Error: Extension directory not found: /usr/local/share/.config/yarn/global/node_modules/vue-devtools/vender/
```

应该怎么解决？

2021-08-08 07:29 UTC, lixiang810 commented
@ForkKILLET 这个错不会影响运行，你应该没定位到错误

2021-08-08 08:05 UTC, ForkKILLET commented
@lixiang810 updated

2021-08-08 08:51 UTC, lixiang810 commented
> 
> 
> @lixiang810 updated

这个也是正常的错误。你的错误应该是在renderer进程里的，要在窗口的“开发人员工具”的console里面看，而不是在运行`yarn dev`的那个终端里面看，那里面是main抛的错

2021-08-08 09:02 UTC, ForkKILLET commented
> > @lixiang810 updated
> 
> 这个也是正常的错误。你的错误应该是在renderer进程里的，要在窗口的“开发人员工具”的console里面看，而不是在运行`yarn dev`的那个终端里面看，那里面是main抛的错

可是窗口是白屏，根本没跑起来，Element 和 Console 都是空的

2021-08-09 02:29 UTC, Clansty commented
> @lixiang810 updated

怕不是没有 push？

2021-08-09 03:25 UTC, ForkKILLET commented
> > @lixiang810 updated
> 
> 怕不是没有 push？

呃，我是说编辑了报错信息那个回复

2021-11-15 06:08 UTC, closed without merging